language: rust
dist: xenial
addons:
  postgresql: "11"
  apt:
    packages:
    - libssl-dev
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
  - DATABASE_URL="postgres://travis:@127.0.0.1:5433/newsletter"
cache: cargo
rust:
- stable
services:
- postgresql
before_cache: |
  cargo install cargo-tarpaulin
before_script:
- psql -c 'create database newsletter;' -U travis -p 5433
- rustup component add rustfmt
- rustup component add clippy
- cargo install cargo-audit
- cargo install --vers 0.5.7 sqlx-cli --no-default-features --features postgres
- sqlx database create
- sqlx migrate run
- cp ./ci/config.yaml config.yaml
# As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
# everything in one large command instead of multiple commands.
# In this way, the build stops immediately if one of the commands fails.
script: |
  cargo fmt --all -- --check &&
  cargo clippy -- -D warnings &&
  cargo build &&
  cargo test &&
  cargo audit
after_success: |
  cargo tarpaulin --ignore-tests --out Xml
  bash <(curl -s https://codecov.io/bash)