language: rust
dist: bionic
addons:
  apt:
    packages:
    - libssl-dev
cache: cargo
rust:
- stable
services:
- postgresql
env:
- DATABASE_URL="postgres://postgres:@localhost:5432/newsletter"
before_cache: |
  cargo install cargo-tarpaulin
before_script:
- rustup component add rustfmt
- rustup component add clippy
- cargo install cargo-audit
- cargo install --vers 0.5.7 sqlx-cli --no-default-features --features postgres
- sqlx database create
- sqlx migrate run
- cp ./ci/config.yaml config.yaml
# As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
# everything in one large command instead of multiple commands.
# In this way, the build stops immediately if one of the commands fails.
script: |
  cargo fmt --all -- --check &&
  cargo clippy -- -D warnings &&
  cargo build &&
  cargo test &&
  cargo audit
after_success: |
  cargo tarpaulin --ignore-tests --out Xml
  bash <(curl -s https://codecov.io/bash)